#!/tools/bin/python2.7
#
# Confidential and Proprietary Source Code
#
# This Digital Domain Productions, Inc. source code, including without
# limitation any human-readable computer programming code and associated
# documentation (together 'Source Code'), contains valuable confidential,
# proprietary and trade secret information of Digital Domain Productions and is
# protected by the laws of the United States and other countries. Digital
# Domain Productions, Inc. may, from time to time, authorize specific employees
# to use the Source Code internally at Digital Domain Production Inc.'s premises
# solely for developing, updating, and/or troubleshooting the Source Code. Any
# other use of the Source Code, including without limitation any disclosure,
# copying or reproduction, without the prior written authorization of Digital
# Domain Productions, Inc. is strictly prohibited.
#
# Copyright (c) [2011] Digital Domain Productions, Inc. All rights reserved.
#

# $URL: $
# $Date: $
# $Revision: $

"""This illustrates the most basic wrapper"""

import os
from dd.runtime import Application

name = os.path.basename(__file__)
app = Application( 'context.qt_py_convert.Qt_py_convert', program_name='bin/%s' % name )
app.run()

